{% set name = "indic-nlp-library" %}
{% set version = "0.92" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/indic_nlp_library-{{ version }}.tar.gz
  sha256: 5e83e54a1016873cbd7417e5376c12ca87411151760ad92809b2af8824982d73

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - sphinx-argparse
    - sphinx_rtd_theme
    - morfessor
    - pandas
    - numpy

test:
  imports:
    - indic_nlp_library
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/anoopkunchukuttan/indic_nlp_library
  summary: The goal of the Indic NLP Library is to build Python based libraries for common text processing and Natural Language Processing in Indian languages.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://anoopkunchukuttan.github.io/indic_nlp_library/
  dev_url: https://github.com/anoopkunchukuttan/indic_nlp_library/

extra:
  recipe-maintainers:
    - Ubadub
